apiVersion: v1
kind: Service
metadata:
    name: sa-backend-lb
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
        app: sa-backend
